---
- name: install nginx from repo
  yum:
    name: nginx
    state: latest
  tags:
    - nginx-package
    - packages
- name: Create config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  tags:
    nginx-configuration
  notify: Start