---
- name: Reboot
  hosts: all
  become: true
  roles: 
    - seliux
- name: Install nginx package from repo
  hosts: webservers
  become: true
  roles: 
    - client
- name: Install nginx package from repo
  hosts: balancer
  become: true
  roles: 
    - balance
